#!/bin/bash

# Purpose:  generate the ssh config file

if grep -q "File generated at" ~/.ssh/config ; then

(
    echo "######################################################################"
    echo "#   File generated at `date` by $0.  "
    echo "#"
    echo "#            DO NOT CHANGE MANUALLY"
    echo "#"
    echo "#  change the files in ~/.ssh/config.d instead"
    echo "######################################################################"

    if [ -d ~/.ssh/config.d ] ; then
	for f in ~/.ssh/config.d/*.conf; do
	    echo
	    echo "# from $f"
	    cat $f
	done
    fi
) > ~/.ssh/config

chmod 600 ~/.ssh/config


else
    cat <<EOF
Refusing to overwrite your existing .ssh config file.  Please move it
to ~/.ssh/config.d so generation can occur
EOF
   exit 1

fi
